### ISSUE TITLE
Small changes in relative binding free energies depending on the chosen reference ligand

### ISSUE THREAD

**Issue by maxkuhn** [michellab/freenrgworkflows#16]
I have noticed that the calculated ddG values are depending on the reference molecule chosen. That is, ddG between molecules A and B when selecting molecule C as reference may be different compared to the calculation using molecule D as reference. (I have come across this issue when I created a loop to iterate over all ligands in a dataset, selecting each molecule as reference ligand and calculating the relative ddGs based on this selection.)

I had expected to get the same relative ddG value between A and B, regardless of whether C or D is selected as reference ligand. Hence, the regression line should have the same slope for both cases and should only be shifted along the y-axis.

I do understand that the calculation of the relative ddG values is dependent on the distance between molecules. However, I do not see how this should alter the results. Could you enlighten me a little bit on how the code works in detail at this stage?

Some example files:

- This is the code used for analysis as Jupyter Notebook. Please rename the file to .ipynb. (I just had to rename it to .txt to upload it here.)
    - [FreeNRG_Workflow_Test.txt](https://github.com/michellab/freenrgworkflows/files/2836129/FreeNRG_Workflow_Test.txt)
- The archive contains the results of the FEP runs and the files generated by the notebook.
    - [results.zip](https://github.com/michellab/freenrgworkflows/files/2836126/results.zip)
- The pdf contains the plots for ddG(comp) vs. ddG(exp) for each molecule as reference ligand. Five molecules with similar experimental affinities can be seen to have varying computed results. They are circled on every slide
    - [freenrgworkflow_different_results_cdk2.pdf](https://github.com/michellab/freenrgworkflows/files/2836130/freenrgworkflow_different_results_cdk2.pdf)

**Comment by ppxasjsm** [comment]
Hi Max, this does sound suspicious. I am traveling today, but will have a look tomorrow

**Comment by ppxasjsm** [comment]
Hey @maxkuhn finally getting round to looking at this. Do you have a perturbation map of the network you are using? I can obviously generate one, but in case you have an image lying around this would be a lot easier.

**Comment by maxkuhn** [comment]
Hi @ppxasjsm Thanks!
Here is the perturbation map. The simulations in red are not included in the results due to an error in the initial setup of the files.

![cdk2_network](https://user-images.githubusercontent.com/43338350/53180237-1a85ac00-35ed-11e9-96fb-088cb152de59.png)

**Comment by jmichel80** [comment]
@ppxasjsm has this issue been resolved?

**Comment by ppxasjsm** [comment]
I think we had discussed this and there is no easy way to address this issue with the current scheme in which things are done and is dependent on the network structure.

**Comment by jmichel80** [comment]
Could you post a summary of why this variability is observed using the current version of the code for the record. It seems the issue hasn't been fully clarified.

**Comment by ppxasjsm** [comment]
Sure will get back to you on this one!

**Comment by jmichel80** [comment]
Hi @maxkuhn could you share the BACE data you discussed earlier today for us to take a closer look.

**Comment by maxkuhn** [comment]
I have attached two input files for freenrgworkflows (for two different ligands, but the files are obviously the same except for the header) and the corresponding output files. Note that the shift along the y-axis is completely different for some molecules, depending on where they are located in the network. 

[issue16_bace.zip](https://github.com/michellab/freenrgworkflows/files/3763075/issue16_bace.zip)

**Comment by ppxasjsm** [comment]
I have all the data for this and am working on a good explanation. I have been looking at a small toy subset and will try and update you on this either tomorrow or Friday.

**Comment by ppxasjsm** [comment]
This has been addressed now.
