### ISSUE TITLE
Divide by zero error if network is perfect

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/freenrgworkflows#18]
If both forward and backward edge are identical a divide by zero error occurs.

**Comment by jmichel80** [comment]
@ppxasjsm has this issue been resolved?

**Comment by maxkuhn** [comment]
I'd also like to have an update on this.

**Comment by ppxasjsm** [comment]
I'll double check tomorrow and will let you know.

**Comment by ppxasjsm** [comment]
ca5d5e7 fixes this.
