### ISSUE TITLE
Typo in script

### ISSUE THREAD

**Issue by mark-cresset** [michellab/freenrgworkflows#20]
In run_networkanalysis.py, "Weidghted" should be "Weighted".

**Comment by ppxasjsm** [comment]
I will do some tidying of the code this week and try and get a new release by Wednesday with the typo fixed and a couple of other things as well. Thanks for flagging this!

**Comment by ppxasjsm** [comment]
The typo you mention, as well as other are now fixed by
https://github.com/michellab/freenrgworkflows/commit/744920d937f5c8ad8b9ede2a895cc18a2ebbf3f0
