### ISSUE TITLE
recognition of different binding modes for same compounds

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/freenrgworkflows#4]
Experimental and computational free energies only work with identical compound names. 
Introduce nomanclature that will allow evaluation for different binding modes.

**Comment by jmichel80** [comment]
For what it's worth I just wrote the following script to manually merge binding modes after getting the free energies. 

Let's agree now on a nomenclature for compounds

XXXX-BMYYYY means compound XXXX in binding mode YYYY. 


import os,sys
from math import sqrt, exp, log

KT = 0.594

stream = open(sys.argv[1],'r')
buffer = stream.readlines()
stream.close()
mols = {}
for line in buffer:
    if line.startswith("#"):
        continue
    elems = line.split()
    mol = elems[0] 
    nrg = float( elems[1] )
    err = float( elems[3] )
    elems = mol.split("-")
    moln = elems[0]
    try:
        mols[moln]
    except KeyError:
        mols[moln] = []
    mols[moln].append([nrg, err])

#print (mols)

ids = mols.keys()
ids.sort()

for mol in ids:
    nrgtot = 0.0
    errtot = 0.0
    for nrg, err in mols[mol]:
        nrgtot += exp(-nrg/KT)
        errtot += err**2
    nrgtot = -KT*log(nrgtot)
    errtot = sqrt(errtot)
    print ("%s %5.2f +/- %5.2f" % (mol,nrgtot,errtot))

**Comment by ppxasjsm** [comment]
Ok I'll look into this.

**Comment by ppxasjsm** [comment]
Btw, @jmichel80 if you use code tags for code it is easier to read.

**Comment by ppxasjsm** [comment]
Commit 9e5b781 resolves this.
